/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author rubenmp
 */
public class ConversationView extends javax.swing.JPanel {

    /**
     * Creates new form ConversationView
     */
    public ConversationView() {
        initComponents();
    }

    
      static Color colors[] = { Color.RED, Color.ORANGE, Color.YELLOW, Color.GREEN, Color.BLUE,
      Color.MAGENTA };

    static void add(JTabbedPane tabbedPane, String label) {
      int count = tabbedPane.getTabCount();
      JButton button = new JButton(label);
      button.setBackground(colors[count]);
      tabbedPane.addTab(label, new ImageIcon("yourFile.gif"), button, label);
    }

    public static void main(String args[]) {
      JFrame frame = new JFrame("Tabbed Pane Sample");
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

      JTabbedPane tabbedPane = new JTabbedPane();
      tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
      String titles[] = { "A", "B", "C", "D", "E", "F" };
      for (int i = 0, n = titles.length; i < n; i++) {
        add(tabbedPane, titles[i]);
      }

      frame.add(tabbedPane, BorderLayout.CENTER);
      frame.setSize(400, 150);
      frame.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
